# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: AIEducationLabs.NightDimmer
PackageVersion: 1.0.0
InstallerType: portable
MinimumOSVersion: 10.0.17763.0
ReleaseDate: 2026-09-17
Commands:
  - nightdimmer
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/AI-Education-Labs/night-dimmer/releases/download/v1.0.0/NightDimmer.exe
    InstallerSha256: 74591C1F936CB22679FA29DB67B9772AEA667C94E7C7E30C477BE640BA004538
  - Architecture: x86
    InstallerUrl: https://github.com/AI-Education-Labs/night-dimmer/releases/download/v1.0.0/NightDimmer.exe
    InstallerSha256: 74591C1F936CB22679FA29DB67B9772AEA667C94E7C7E30C477BE640BA004538
ManifestType: installer
ManifestVersion: 1.6.0
